DROP TABLE IF EXISTS admin;

CREATE TABLE admin (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstname VARCHAR (255) NOT NULL,
  lastname VARCHAR (255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  pwd VARCHAR(255) NOT NULL,
  img VARCHAR(255) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3;

DROP TABLE IF EXISTS projects;

CREATE TABLE projects(
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  techno VARCHAR(255) DEFAULT NULL,
  status VARCHAR(255) DEFAULT NULL,
  start DATE DEFAULT NULL,
  end DATE DEFAULT NULL,
  online VARCHAR(255) DEFAULT NULL,
  admin_id INT DEFAULT NULL,
  CONSTRAINT fk_project_admin FOREIGN KEY (admin_id) REFERENCES admin(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3;

DROP TABLE IF EXISTS picture;

CREATE TABLE picture(
  id INT PRIMARY KEY AUTO_INCREMENT,
  img VARCHAR(255) NOT NULL,
  legende VARCHAR(255) DEFAULT NULL,
  projects_id INT DEFAULT NULL,
  admin_id INT DEFAULT NULL,
  CONSTRAINT fk_projects_id FOREIGN KEY (projects_id) REFERENCES projects(id),
  CONSTRAINT fk_admin_id FOREIGN KEY (admin_id) REFERENCES admin(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3;
